### ISSUE TITLE
Doesn't work on Catalina

### ISSUE THREAD

**Issue by hazarek** [Watson1978/QLMarkdownGFM#4]
Doesn't work on Catalina

I checked.
- No conflicts with other generators. :heavy_check_mark:
- Generator is active. :heavy_check_mark:

**Comment by Watson1978** [comment]
Seems macOS 10.15 Gatekeeper rejects QuickLook plugins which render HTML.

So far, when you can disable Gatekeeper as following command at once, the plugin will work. 
```
$ sudo spctl --master-disable
```

(You can also enable GateKeeper as following)
```
$ sudo spctl --master-enable
$ spctl --status
```

**Comment by hazarek** [comment]
> Seems macOS 10.15 Gatekeeper rejects QuickLook plugins which render HTML.
> So far, when you can disable Gatekeeper as following command at once, the plugin will work.

without gatekeeper also does not work. I tried every way. Other plugins which render HTML are working with gatekeeper. ( [qlmarkdown](https://github.com/toland/qlmarkdown/pull/90#issuecomment-544636334), [SourceCodeSyntaxHighlight](https://github.com/sbarex/SourceCodeSyntaxHighlight) )

**Comment by pryley** [comment]
It worked for me like this:

1. Install the plugin
2. Reset Quick Look: `qlmanage -r`
3. Open a Finder window and attempt to Quick Look a markdown file
4. Close the Finder window
5. Open Preferences > Security & Privacy and click "Allow Anyway"
6. Quit Preferences
7. Remove the quarantine attributes: `xattr -d -r com.apple.quarantine ~/Library/QuickLook/`
8. Reset Quick Look: `qlmanage -r`

**Comment by hazarek** [comment]
Also doesn't work on Big Sur

**Comment by pryley** [comment]
@hazarek

1. Download the release
2. Remove the quarantine flag
3. Install

```bash
xattr -rd ~/Downloads/QLMarkdownGFM.qlgenerator.zip
```

However, I no longer use this. On Catalina I used [Glance](https://github.com/samuelmeuli/glance), but that stopped working on Big Sur so I switched to [iPreview](https://findergg.com).

Removing the quarantine **does work** in Catalina, however I have not tested this in Big Sur and the problem may be due to a lack of codesigning all included libraries used in the QL plugin.
